#!/bin/bash

# Define the relative path to the script
RELATIVE_PATH=$1

CURRENT_DIR=$(cd "$(dirname "$0")" && pwd)
CURRENT_DIR=${CURRENT_DIR%/*}

# Construct the full path to the script
SCRIPT_FULL_PATH="$CURRENT_DIR/$RELATIVE_PATH/sh"


echo "core-sdk - Change detected. Running build..."
"$SCRIPT_FULL_PATH"/build packages/core-sdk
