#!/bin/bash

# Get the directory of the current script
SH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Get the parent directory of the obtained path
PARENT_DIR="$(dirname "$SH_DIR")"


CORE_SDK_CHANGES_COUNT="$( git diff origin/main HEAD -- packages/core-sdk/ | grep -c version || echo "" )"
if [ "$CHANGES_COUNT" != "0" ]; then
    echo "core-sdk - Change detected. Running build..."
    "$PARENT_DIR/packages/core-sdk/sh/build"
else
    echo "core-sdk - No Change detected."
fi
