#!/bin/bash

# Get the directory of the current script
SH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Get the parent directory of the obtained path
PARENT_DIR="$(dirname "$SH_DIR")"


CORE_SDK_CHANGES_COUNT="$( git diff origin/main HEAD -- packages/core-sdk/ | grep -cE '^\+\+\+' )"
if [ "$CORE_SDK_CHANGES_COUNT" != "0" ]; then
    echo "core-sdk - Change detected. Running build..."
    "$PARENT_DIR/packages/core-sdk/sh/build"
else
    echo "core-sdk - No Change detected."
fi


MONGODB_SDK_CHANGES_COUNT="$( git diff origin/main HEAD -- packages/mongodb-sdk/ | grep -cE '^\+\+\+' )"
if [ "$MONGODB_SDK_CHANGES_COUNT" != "0" ]; then
    echo "mongodb-sdk - Change detected. Running build..."
    "$PARENT_DIR/packages/mongodb-sdk/sh/build"
else
    echo "mongodb-sdk - No Change detected."
fi


GATEWAY_CHANGES_COUNT="$( git diff origin/main HEAD -- services/gateway/ | grep -cE '^\+\+\+' )"
if [ "$GATEWAY_CHANGES_COUNT" != "0" ]; then
    echo "gateway - Change detected. Running build..."
    "$PARENT_DIR/services/gateway/sh/build"
else
    echo "gateway - No Change detected."
fi
