#!/bin/bash

set -e

# Get the directory of the current script
SH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Get the parent directory of the obtained path
PARENT_DIR="$(dirname "$SH_DIR")"


# Check for uncommitted changes
if [[ -n $(git status "$PARENT_DIR" -s) ]]; then
    echo "There are uncommitted changes. Exiting publish script."
    exit 1
fi

TARGET_REF=${TARGET_REF:-origin/main}
SOURCE_REF=${SOURCE_REF:-HEAD}

# Check for changes in core-sdk
CORE_SDK_CHANGES_COUNT="$( git diff "$TARGET_REF" "$SOURCE_REF" packages/core-sdk/pom.xml | grep -cE '^\+\+\+' )" || true
if [ "$CORE_SDK_CHANGES_COUNT" != "0" ]; then
    echo "core-sdk - Change detected. Running build..."
    "$PARENT_DIR/packages/core-sdk/sh/publish"
else
    echo "core-sdk - No Change detected."
fi


# Check for changes in mongodb-sdk
MONGODB_SDK_CHANGES_COUNT="$( git diff "$TARGET_REF" "$SOURCE_REF" packages/mongodb-sdk/pom.xml | grep -cE '^\+\+\+' )" || true
if [ "$MONGODB_SDK_CHANGES_COUNT" != "0" ]; then
    echo "mongodb-sdk - Change detected. Running build..."
    "$PARENT_DIR/packages/mongodb-sdk/sh/publish"
else
    echo "mongodb-sdk - No Change detected."
fi

# Check for changes in mongodb-sdk
PUBSUB_SDK_CHANGES_COUNT="$( git diff "$TARGET_REF" "$SOURCE_REF" packages/pubsub-sdk/pom.xml | grep -cE '^\+\+\+' )" || true
if [ "$PUBSUB_SDK_CHANGES_COUNT" != "0" ]; then
    echo "pubsub-sdk - Change detected. Running build..."
    "$PARENT_DIR/packages/pubsub-sdk/sh/publish"
else
    echo "pubsub-sdk - No Change detected."
fi


# Check for changes in gateway
GATEWAY_CHANGES_COUNT="$( git diff "$TARGET_REF" "$SOURCE_REF" services/gateway/pom.xml | grep -cE '^\+\+\+' )" || true
if [ "$GATEWAY_CHANGES_COUNT" != "0" ]; then
    echo "gateway - Change detected. Running build..."
    "$PARENT_DIR/services/gateway/sh/publish"
else
    echo "gateway - No Change detected."
fi

echo "Running integration testing ..."
"$PARENT_DIR/services/integration-testing/sh/build"
