#!/bin/bash

set -e
# shellcheck disable=SC2034
SH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# shellcheck disable=SC2034
ROOT_DIR="$(dirname "$SH_DIR")"

# This script will do shell
# scripts static checking
# HELP="Usage: sh/check"

echo "Shell check"

docker run --rm \
    -v "$ROOT_DIR:/mnt" \
    koalaman/shellcheck:latest ./sh/* ./*/sh/* ./*/*/sh/* ./*/*/*/sh/*
