version: '4'

services:
  mongodb:
    image: mongo:7.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
      MONGO_INITDB_DATABASE: gateway_db
    ports:
      - 27017:27017
    volumes:
      - /integration

  gateway:
    image: openjdk:17
    depends_on: 
      - mongodb
    environment:
      MONGODB_USER: mongodb_user
      MONGODB_PASSWORD: mongodb_password
      MONGODB_HOSTNAME: mongodb
      MONGODB_DATABASE_NAME: gateway_db
      MONGODB_PORT: 27017
    ports:
      - 8080:8080
    volumes:
      - $INTEGRATION_TESTING_GATEWAY:/opt/gateway.jar
    command: java -jar /opt/gateway.jar

  tests:
    image: maven:3.8.5-openjdk-17-slim
    depends_on: 
      - mongodb
      - gateway
    environment:
      REPO_USERNAME: $REPO_USERNAME
      REPO_TOKEN: $REPO_TOKEN
    volumes:
      - $PARENT_DIR:/opt/maven/
      - $PROJECT_DIR/.m2:/root/.m2/repository
    working_dir: /opt/maven
    command: mvn clean install -s settings.xml
