version: '3.8'

services:
  mongodb:
    image: mongo:7.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
      MONGO_INITDB_DATABASE: gateway_db
    ports:
      - 27017:27017
    volumes:
      - /integration

  kafka:
    image: bitnami/kafka:3.5.2
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    ports:
      - 9092:9092

  gateway:
    image: openjdk:17
    depends_on: 
      - mongodb
      - kafka
    environment:
      MONGODB_USER: mongodb_user
      MONGODB_PASSWORD: mongodb_password
      MONGODB_HOSTNAME: mongodb
      MONGODB_DATABASE_NAME: gateway_db
      MONGODB_PORT: 27017
    ports:
      - 8080:8080
    volumes:
      - $INTEGRATION_TESTING_GATEWAY:/opt/gateway.jar
    command: java -jar /opt/gateway.jar

  mongodb-storage:
    image: openjdk:17
    depends_on: 
      - mongodb
      - kafka
    environment:
      MONGODB_USER: mongodb_user
      MONGODB_PASSWORD: mongodb_password
      MONGODB_HOSTNAME: mongodb
      MONGODB_DATABASE_NAME: gateway_db
      MONGODB_PORT: 27017
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_GROUP_ID: kafka-group-id
      KAFKA_TOPIC: users_topic
    volumes:
      - $INTEGRATION_TESTING_MONGODB_STORAGE:/opt/mongodb-storage.jar
    command: java -jar /opt/mongodb-storage.jar

  tests:
    image: maven:3.8.5-openjdk-17-slim
    depends_on: 
      - mongodb
      - kafka
      - gateway
    environment:
      REPO_USERNAME: $REPO_USERNAME
      REPO_TOKEN: $REPO_TOKEN
    volumes:
      - $PARENT_DIR:/opt/maven/
      - $PROJECT_DIR/.m2:/root/.m2/repository
    working_dir: /opt/maven
    command: mvn clean install -s settings.xml
