version: '4'

services:
  mongodb:
    image: mongo:7.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
      MONGO_INITDB_DATABASE: gateway_db
    ports:
      - 27017:27017
    volumes:
      - /integration

  gateway:
    image: etidahouse/java-hexagonal-gateway:latest
    depends_on: 
      - mongodb
    environment:
      MONGODB_USER: mongodb_user
      MONGODB_PASSWORD: mongodb_password
      MONGODB_HOSTNAME: mongodb
      MONGODB_DATABASE_NAME: gateway_db
      MONGODB_PORT: 27017
    ports:
      - 8080:8080
