name: CI Publish

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set Target Ref
        run: echo "TARGET_REF=${{ github.event.before }}" >> $GITHUB_ENV

      - name: Set Source Ref
        run: echo "SOURCE_REF=${{ github.event.after }}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: env

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          token: ${{ secrets.REPO_TOKEN}}

      - name: Set up Git Configuration
        run: |
          git config --global user.email "e-begon@hotmail.fr"
          git config --global user.name "etidahouse"

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Run Publish
        run: sh/ci-publish
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
