name: CI Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set Target Ref
        run: echo "TARGET_REF=${{ github.event.before }}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: env

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.before }}
          fetch-depth: 0
          token: ${{ secrets.REPO_TOKEN}}

      - name: Set up Git Configuration
        run: |
          git config --global user.email "e-begon@hotmail.fr"
          git config --global user.name "etidahouse"
          git fetch --depth=0 --no-tags origin main

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Run Publish
        run: sh/ci-publish
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
