name: CI Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git Configuration
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git fetch --no-tags origin main

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Run Publish
        run: sh/ci-publish
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
